version: '3'
services:
    challenge-db:
        image: mongo:4.2.12-bionic
        ports:
            - 27017:27017
        environment:
            - MONGO_INITDB_ROOT_USERNAME=challengedb_user
            - MONGO_INITDB_ROOT_PASSWORD=challengedb_pass
        volumes:
            - mongodb_dev:/data/db
volumes:
    mongodb_dev:
        driver: local